// GENERATED by scripts/reactions-mirror.mjs — DO NOT EDIT BY HAND.
// Re-run `node scripts/reactions-mirror.mjs` to regenerate (see script header).
// Source: https://googlefonts.github.io/noto-emoji-animation/data/api.json
// Catalog last-modified: Fri, 24 Apr 2026 17:51:05 GMT
// Generated: 2026-07-10T12:42:47.229Z — 609 entries, Noto catalog order.
// Filter: base emojis only — skin-tone variants (1f3fb–1f3ff modifiers) dropped.

/** One entry per Noto animated emoji. Asset URLs are built from
 *  REACTION_ASSET_BASE (app/constants/assets.ts): `${base}/${code}/lottie.json`
 *  and `${base}/${code}/emoji.svg`. */
export interface ReactionManifestEntry {
  /** Lowercase hex codepoint(s); multi-codepoint joined by "_" (e.g. "1faf4_1f3fe"). */
  readonly code: string
  readonly name: string
  readonly category: string
  readonly tags: readonly string[]
}

export const REACTIONS: readonly ReactionManifestEntry[] = [
  {
    "code": "1f600",
    "name": "smile",
    "category": "Smileys and emotions",
    "tags": [
      "smile"
    ]
  },
  {
    "code": "1f603",
    "name": "smile with big eyes",
    "category": "Smileys and emotions",
    "tags": [
      "smile-with-big-eyes"
    ]
  },
  {
    "code": "1f604",
    "name": "grin",
    "category": "Smileys and emotions",
    "tags": [
      "grin"
    ]
  },
  {
    "code": "1f601",
    "name": "grinning",
    "category": "Smileys and emotions",
    "tags": [
      "grinning"
    ]
  },
  {
    "code": "1f606",
    "name": "laughing",
    "category": "Smileys and emotions",
    "tags": [
      "laughing"
    ]
  },
  {
    "code": "1f605",
    "name": "grin sweat",
    "category": "Smileys and emotions",
    "tags": [
      "grin-sweat"
    ]
  },
  {
    "code": "1f602",
    "name": "joy",
    "category": "Smileys and emotions",
    "tags": [
      "joy"
    ]
  },
  {
    "code": "1f923",
    "name": "rofl",
    "category": "Smileys and emotions",
    "tags": [
      "rofl"
    ]
  },
  {
    "code": "1f62d",
    "name": "loudly crying",
    "category": "Smileys and emotions",
    "tags": [
      "loudly-crying"
    ]
  },
  {
    "code": "1f609",
    "name": "wink",
    "category": "Smileys and emotions",
    "tags": [
      "wink"
    ]
  },
  {
    "code": "1f617",
    "name": "kissing",
    "category": "Smileys and emotions",
    "tags": [
      "kissing"
    ]
  },
  {
    "code": "1f619",
    "name": "kissing smiling eyes",
    "category": "Smileys and emotions",
    "tags": [
      "kissing-smiling-eyes"
    ]
  },
  {
    "code": "1f61a",
    "name": "kissing closed eyes",
    "category": "Smileys and emotions",
    "tags": [
      "kissing-closed-eyes"
    ]
  },
  {
    "code": "1f618",
    "name": "kissing heart",
    "category": "Smileys and emotions",
    "tags": [
      "kissing-heart"
    ]
  },
  {
    "code": "1f970",
    "name": "heart face",
    "category": "Smileys and emotions",
    "tags": [
      "heart-face",
      "3-hearts"
    ]
  },
  {
    "code": "1f60d",
    "name": "heart eyes",
    "category": "Smileys and emotions",
    "tags": [
      "heart-eyes"
    ]
  },
  {
    "code": "1f929",
    "name": "star struck",
    "category": "Smileys and emotions",
    "tags": [
      "star-struck"
    ]
  },
  {
    "code": "1f973",
    "name": "partying face",
    "category": "Smileys and emotions",
    "tags": [
      "partying-face"
    ]
  },
  {
    "code": "1fae0",
    "name": "melting",
    "category": "Smileys and emotions",
    "tags": [
      "melting"
    ]
  },
  {
    "code": "1f643",
    "name": "upside down face",
    "category": "Smileys and emotions",
    "tags": [
      "upside-down-face"
    ]
  },
  {
    "code": "1f642",
    "name": "slightly happy",
    "category": "Smileys and emotions",
    "tags": [
      "slightly-happy"
    ]
  },
  {
    "code": "1f972",
    "name": "happy cry",
    "category": "Smileys and emotions",
    "tags": [
      "happy-cry"
    ]
  },
  {
    "code": "1f979",
    "name": "holding back tears",
    "category": "Smileys and emotions",
    "tags": [
      "holding-back-tears"
    ]
  },
  {
    "code": "1f60a",
    "name": "blush",
    "category": "Smileys and emotions",
    "tags": [
      "blush"
    ]
  },
  {
    "code": "263a_fe0f",
    "name": "warm smile",
    "category": "Smileys and emotions",
    "tags": [
      "warm-smile"
    ]
  },
  {
    "code": "1f60c",
    "name": "relieved",
    "category": "Smileys and emotions",
    "tags": [
      "relieved"
    ]
  },
  {
    "code": "1f642_200d_2195_fe0f",
    "name": "head nod",
    "category": "Smileys and emotions",
    "tags": [
      "head-nod"
    ]
  },
  {
    "code": "1f642_200d_2194_fe0f",
    "name": "head shake",
    "category": "Smileys and emotions",
    "tags": [
      "head-shake"
    ]
  },
  {
    "code": "1f60f",
    "name": "smirk",
    "category": "Smileys and emotions",
    "tags": [
      "smirk"
    ]
  },
  {
    "code": "1f924",
    "name": "drool",
    "category": "Smileys and emotions",
    "tags": [
      "drool"
    ]
  },
  {
    "code": "1f60b",
    "name": "yum",
    "category": "Smileys and emotions",
    "tags": [
      "yum"
    ]
  },
  {
    "code": "1f61b",
    "name": "stuck out tongue",
    "category": "Smileys and emotions",
    "tags": [
      "stuck-out-tongue"
    ]
  },
  {
    "code": "1f61d",
    "name": "squinting tongue",
    "category": "Smileys and emotions",
    "tags": [
      "squinting-tongue"
    ]
  },
  {
    "code": "1f61c",
    "name": "winky tongue",
    "category": "Smileys and emotions",
    "tags": [
      "winky-tongue"
    ]
  },
  {
    "code": "1f92a",
    "name": "zany face",
    "category": "Smileys and emotions",
    "tags": [
      "zany-face"
    ]
  },
  {
    "code": "1faea",
    "name": "distorted face",
    "category": "Smileys and emotions",
    "tags": [
      "distorted-face"
    ]
  },
  {
    "code": "1f614",
    "name": "pensive",
    "category": "Smileys and emotions",
    "tags": [
      "pensive"
    ]
  },
  {
    "code": "1f97a",
    "name": "pleading",
    "category": "Smileys and emotions",
    "tags": [
      "pleading"
    ]
  },
  {
    "code": "1f62c",
    "name": "grimacing",
    "category": "Smileys and emotions",
    "tags": [
      "grimacing"
    ]
  },
  {
    "code": "1f611",
    "name": "expressionless",
    "category": "Smileys and emotions",
    "tags": [
      "expressionless"
    ]
  },
  {
    "code": "1f610",
    "name": "neutral face",
    "category": "Smileys and emotions",
    "tags": [
      "neutral-face"
    ]
  },
  {
    "code": "1f636",
    "name": "mouth none",
    "category": "Smileys and emotions",
    "tags": [
      "mouth-none"
    ]
  },
  {
    "code": "1f636_200d_1f32b_fe0f",
    "name": "face in clouds",
    "category": "Smileys and emotions",
    "tags": [
      "face-in-clouds",
      "lost"
    ]
  },
  {
    "code": "1fae5",
    "name": "dotted line face",
    "category": "Smileys and emotions",
    "tags": [
      "dotted-line-face",
      "invisible"
    ]
  },
  {
    "code": "1f910",
    "name": "zipper face",
    "category": "Smileys and emotions",
    "tags": [
      "zipper-face"
    ]
  },
  {
    "code": "1fae1",
    "name": "salute",
    "category": "Smileys and emotions",
    "tags": [
      "salute"
    ]
  },
  {
    "code": "1f914",
    "name": "thinking face",
    "category": "Smileys and emotions",
    "tags": [
      "thinking-face"
    ]
  },
  {
    "code": "1f92b",
    "name": "shushing face",
    "category": "Smileys and emotions",
    "tags": [
      "shushing-face"
    ]
  },
  {
    "code": "1fae2",
    "name": "hand over mouth",
    "category": "Smileys and emotions",
    "tags": [
      "hand-over-mouth"
    ]
  },
  {
    "code": "1f92d",
    "name": "smiling eyes with hand over mouth",
    "category": "Smileys and emotions",
    "tags": [
      "smiling-eyes-with-hand-over-mouth",
      "chuckling"
    ]
  },
  {
    "code": "1f971",
    "name": "yawn",
    "category": "Smileys and emotions",
    "tags": [
      "yawn"
    ]
  },
  {
    "code": "1f917",
    "name": "hug face",
    "category": "Smileys and emotions",
    "tags": [
      "hug-face"
    ]
  },
  {
    "code": "1fae3",
    "name": "peeking",
    "category": "Smileys and emotions",
    "tags": [
      "peeking"
    ]
  },
  {
    "code": "1f631",
    "name": "screaming",
    "category": "Smileys and emotions",
    "tags": [
      "screaming"
    ]
  },
  {
    "code": "1f928",
    "name": "raised eyebrow",
    "category": "Smileys and emotions",
    "tags": [
      "raised-eyebrow"
    ]
  },
  {
    "code": "1f9d0",
    "name": "monocle",
    "category": "Smileys and emotions",
    "tags": [
      "monocle"
    ]
  },
  {
    "code": "1f612",
    "name": "unamused",
    "category": "Smileys and emotions",
    "tags": [
      "unamused"
    ]
  },
  {
    "code": "1f644",
    "name": "rolling eyes",
    "category": "Smileys and emotions",
    "tags": [
      "rolling-eyes"
    ]
  },
  {
    "code": "1f62e_200d_1f4a8",
    "name": "exhale",
    "category": "Smileys and emotions",
    "tags": [
      "exhale"
    ]
  },
  {
    "code": "1f624",
    "name": "triumph",
    "category": "Smileys and emotions",
    "tags": [
      "triumph"
    ]
  },
  {
    "code": "1f620",
    "name": "angry",
    "category": "Smileys and emotions",
    "tags": [
      "angry"
    ]
  },
  {
    "code": "1f621",
    "name": "rage",
    "category": "Smileys and emotions",
    "tags": [
      "rage"
    ]
  },
  {
    "code": "1f92c",
    "name": "cursing",
    "category": "Smileys and emotions",
    "tags": [
      "cursing"
    ]
  },
  {
    "code": "1f61e",
    "name": "sad",
    "category": "Smileys and emotions",
    "tags": [
      "sad"
    ]
  },
  {
    "code": "1f613",
    "name": "sweat",
    "category": "Smileys and emotions",
    "tags": [
      "sweat",
      "downcast"
    ]
  },
  {
    "code": "1f61f",
    "name": "worried",
    "category": "Smileys and emotions",
    "tags": [
      "worried"
    ]
  },
  {
    "code": "1f625",
    "name": "concerned",
    "category": "Smileys and emotions",
    "tags": [
      "concerned"
    ]
  },
  {
    "code": "1f622",
    "name": "cry",
    "category": "Smileys and emotions",
    "tags": [
      "cry"
    ]
  },
  {
    "code": "2639_fe0f",
    "name": "big frown",
    "category": "Smileys and emotions",
    "tags": [
      "big-frown"
    ]
  },
  {
    "code": "1f641",
    "name": "frown",
    "category": "Smileys and emotions",
    "tags": [
      "frown"
    ]
  },
  {
    "code": "1fae4",
    "name": "diagonal mouth",
    "category": "Smileys and emotions",
    "tags": [
      "diagonal-mouth"
    ]
  },
  {
    "code": "1f615",
    "name": "slightly frowning",
    "category": "Smileys and emotions",
    "tags": [
      "slightly-frowning"
    ]
  },
  {
    "code": "1f630",
    "name": "anxious with sweat",
    "category": "Smileys and emotions",
    "tags": [
      "anxious-with-sweat"
    ]
  },
  {
    "code": "1f628",
    "name": "scared",
    "category": "Smileys and emotions",
    "tags": [
      "scared"
    ]
  },
  {
    "code": "1f627",
    "name": "anguished",
    "category": "Smileys and emotions",
    "tags": [
      "anguished"
    ]
  },
  {
    "code": "1f626",
    "name": "gasp",
    "category": "Smileys and emotions",
    "tags": [
      "gasp"
    ]
  },
  {
    "code": "1f62e",
    "name": "mouth open",
    "category": "Smileys and emotions",
    "tags": [
      "mouth-open"
    ]
  },
  {
    "code": "1f62f",
    "name": "surprised",
    "category": "Smileys and emotions",
    "tags": [
      "surprised",
      "hushed"
    ]
  },
  {
    "code": "1f632",
    "name": "astonished",
    "category": "Smileys and emotions",
    "tags": [
      "astonished"
    ]
  },
  {
    "code": "1f633",
    "name": "flushed",
    "category": "Smileys and emotions",
    "tags": [
      "flushed"
    ]
  },
  {
    "code": "1f92f",
    "name": "mind blown",
    "category": "Smileys and emotions",
    "tags": [
      "mind-blown",
      "exploding-head"
    ]
  },
  {
    "code": "1f616",
    "name": "scrunched mouth",
    "category": "Smileys and emotions",
    "tags": [
      "scrunched-mouth",
      "confounded",
      "zigzag-mouth"
    ]
  },
  {
    "code": "1f623",
    "name": "scrunched eyes",
    "category": "Smileys and emotions",
    "tags": [
      "scrunched-eyes",
      "persevering"
    ]
  },
  {
    "code": "1f629",
    "name": "weary",
    "category": "Smileys and emotions",
    "tags": [
      "weary"
    ]
  },
  {
    "code": "1f62b",
    "name": "distraught",
    "category": "Smileys and emotions",
    "tags": [
      "distraught"
    ]
  },
  {
    "code": "1f635",
    "name": "x eyes",
    "category": "Smileys and emotions",
    "tags": [
      "x-eyes"
    ]
  },
  {
    "code": "1f635_200d_1f4ab",
    "name": "dizzy face",
    "category": "Smileys and emotions",
    "tags": [
      "dizzy-face"
    ]
  },
  {
    "code": "1fae8",
    "name": "shaking face",
    "category": "Smileys and emotions",
    "tags": [
      "shaking-face"
    ]
  },
  {
    "code": "1f974",
    "name": "woozy",
    "category": "Smileys and emotions",
    "tags": [
      "woozy"
    ]
  },
  {
    "code": "1f975",
    "name": "hot face",
    "category": "Smileys and emotions",
    "tags": [
      "hot-face",
      "sweat-face"
    ]
  },
  {
    "code": "1f976",
    "name": "cold face",
    "category": "Smileys and emotions",
    "tags": [
      "cold-face"
    ]
  },
  {
    "code": "1f922",
    "name": "sick",
    "category": "Smileys and emotions",
    "tags": [
      "sick",
      "nauseated"
    ]
  },
  {
    "code": "1f92e",
    "name": "vomit",
    "category": "Smileys and emotions",
    "tags": [
      "vomit"
    ]
  },
  {
    "code": "1fae9",
    "name": "tired",
    "category": "Smileys and emotions",
    "tags": [
      "tired",
      "bags-under-eyes"
    ]
  },
  {
    "code": "1f634",
    "name": "sleep",
    "category": "Smileys and emotions",
    "tags": [
      "sleep"
    ]
  },
  {
    "code": "1f62a",
    "name": "sleepy",
    "category": "Smileys and emotions",
    "tags": [
      "sleepy"
    ]
  },
  {
    "code": "1f927",
    "name": "sneeze",
    "category": "Smileys and emotions",
    "tags": [
      "sneeze"
    ]
  },
  {
    "code": "1f912",
    "name": "thermometer face",
    "category": "Smileys and emotions",
    "tags": [
      "thermometer-face"
    ]
  },
  {
    "code": "1f915",
    "name": "bandage face",
    "category": "Smileys and emotions",
    "tags": [
      "bandage-face"
    ]
  },
  {
    "code": "1f637",
    "name": "mask",
    "category": "Smileys and emotions",
    "tags": [
      "mask"
    ]
  },
  {
    "code": "1f925",
    "name": "liar",
    "category": "Smileys and emotions",
    "tags": [
      "liar"
    ]
  },
  {
    "code": "1f607",
    "name": "halo",
    "category": "Smileys and emotions",
    "tags": [
      "halo",
      "innocent"
    ]
  },
  {
    "code": "1f920",
    "name": "cowboy",
    "category": "Smileys and emotions",
    "tags": [
      "cowboy"
    ]
  },
  {
    "code": "1f911",
    "name": "money face",
    "category": "Smileys and emotions",
    "tags": [
      "money-face"
    ]
  },
  {
    "code": "1f913",
    "name": "nerd face",
    "category": "Smileys and emotions",
    "tags": [
      "nerd-face"
    ]
  },
  {
    "code": "1f60e",
    "name": "sunglasses face",
    "category": "Smileys and emotions",
    "tags": [
      "sunglasses-face"
    ]
  },
  {
    "code": "1f978",
    "name": "disguise",
    "category": "Smileys and emotions",
    "tags": [
      "disguise"
    ]
  },
  {
    "code": "1f921",
    "name": "clown",
    "category": "Smileys and emotions",
    "tags": [
      "clown"
    ]
  },
  {
    "code": "1f4a9",
    "name": "poop",
    "category": "Smileys and emotions",
    "tags": [
      "poop"
    ]
  },
  {
    "code": "1f608",
    "name": "imp smile",
    "category": "Smileys and emotions",
    "tags": [
      "imp-smile"
    ]
  },
  {
    "code": "1f47f",
    "name": "imp frown",
    "category": "Smileys and emotions",
    "tags": [
      "imp-frown"
    ]
  },
  {
    "code": "1f47b",
    "name": "ghost",
    "category": "Smileys and emotions",
    "tags": [
      "ghost"
    ]
  },
  {
    "code": "1f480",
    "name": "skull",
    "category": "Smileys and emotions",
    "tags": [
      "skull"
    ]
  },
  {
    "code": "1f916",
    "name": "robot",
    "category": "Smileys and emotions",
    "tags": [
      "robot"
    ]
  },
  {
    "code": "1f479",
    "name": "ogre",
    "category": "Smileys and emotions",
    "tags": [
      "ogre"
    ]
  },
  {
    "code": "2603_fe0f",
    "name": "snowman with snow",
    "category": "Smileys and emotions",
    "tags": [
      "snowman-with-snow"
    ]
  },
  {
    "code": "26c4",
    "name": "snowman",
    "category": "Smileys and emotions",
    "tags": [
      "snowman"
    ]
  },
  {
    "code": "1f47d",
    "name": "alien",
    "category": "Smileys and emotions",
    "tags": [
      "alien"
    ]
  },
  {
    "code": "1f47e",
    "name": "alien monster",
    "category": "Smileys and emotions",
    "tags": [
      "alien-monster"
    ]
  },
  {
    "code": "1f31a",
    "name": "moon face new",
    "category": "Smileys and emotions",
    "tags": [
      "moon-face-new"
    ]
  },
  {
    "code": "1f31d",
    "name": "moon face full",
    "category": "Smileys and emotions",
    "tags": [
      "moon-face-full"
    ]
  },
  {
    "code": "1f31e",
    "name": "sun with face",
    "category": "Smileys and emotions",
    "tags": [
      "sun-with-face"
    ]
  },
  {
    "code": "1f31b",
    "name": "moon face first quarter",
    "category": "Smileys and emotions",
    "tags": [
      "moon-face-first-quarter"
    ]
  },
  {
    "code": "1f31c",
    "name": "moon face last quarter",
    "category": "Smileys and emotions",
    "tags": [
      "moon-face-last-quarter"
    ]
  },
  {
    "code": "1f63a",
    "name": "smiley cat",
    "category": "Smileys and emotions",
    "tags": [
      "smiley-cat"
    ]
  },
  {
    "code": "1f638",
    "name": "smile cat",
    "category": "Smileys and emotions",
    "tags": [
      "smile-cat"
    ]
  },
  {
    "code": "1f639",
    "name": "joy cat",
    "category": "Smileys and emotions",
    "tags": [
      "joy-cat"
    ]
  },
  {
    "code": "1f63b",
    "name": "heart eyes cat",
    "category": "Smileys and emotions",
    "tags": [
      "heart-eyes-cat"
    ]
  },
  {
    "code": "1f63c",
    "name": "smirk cat",
    "category": "Smileys and emotions",
    "tags": [
      "smirk-cat"
    ]
  },
  {
    "code": "1f63d",
    "name": "kissing cat",
    "category": "Smileys and emotions",
    "tags": [
      "kissing-cat"
    ]
  },
  {
    "code": "1f640",
    "name": "scream cat",
    "category": "Smileys and emotions",
    "tags": [
      "scream-cat"
    ]
  },
  {
    "code": "1f63f",
    "name": "crying cat face",
    "category": "Smileys and emotions",
    "tags": [
      "crying-cat-face"
    ]
  },
  {
    "code": "1f63e",
    "name": "pouting cat",
    "category": "Smileys and emotions",
    "tags": [
      "pouting-cat"
    ]
  },
  {
    "code": "1f648",
    "name": "see no evil monkey",
    "category": "Smileys and emotions",
    "tags": [
      "see-no-evil-monkey"
    ]
  },
  {
    "code": "1f649",
    "name": "hear no evil monkey",
    "category": "Smileys and emotions",
    "tags": [
      "hear-no-evil-monkey"
    ]
  },
  {
    "code": "1f64a",
    "name": "speak no evil monkey",
    "category": "Smileys and emotions",
    "tags": [
      "speak-no-evil-monkey"
    ]
  },
  {
    "code": "2b50",
    "name": "star",
    "category": "Smileys and emotions",
    "tags": [
      "star"
    ]
  },
  {
    "code": "1f31f",
    "name": "glowing star",
    "category": "Smileys and emotions",
    "tags": [
      "glowing-star"
    ]
  },
  {
    "code": "2728",
    "name": "sparkles",
    "category": "Smileys and emotions",
    "tags": [
      "sparkles"
    ]
  },
  {
    "code": "26a1",
    "name": "electricity",
    "category": "Smileys and emotions",
    "tags": [
      "electricity",
      "zap",
      "lightning"
    ]
  },
  {
    "code": "1f4a5",
    "name": "collision",
    "category": "Smileys and emotions",
    "tags": [
      "collision"
    ]
  },
  {
    "code": "1faef",
    "name": "fight",
    "category": "Smileys and emotions",
    "tags": [
      "fight"
    ]
  },
  {
    "code": "1f573_fe0f",
    "name": "hole",
    "category": "Smileys and emotions",
    "tags": [
      "hole"
    ]
  },
  {
    "code": "1f525",
    "name": "fire",
    "category": "Smileys and emotions",
    "tags": [
      "fire",
      "burn",
      "lit"
    ]
  },
  {
    "code": "1f4af",
    "name": "100",
    "category": "Smileys and emotions",
    "tags": [
      "100",
      "one-hundred",
      "hundred",
      "points"
    ]
  },
  {
    "code": "1f389",
    "name": "party popper",
    "category": "Smileys and emotions",
    "tags": [
      "party-popper"
    ]
  },
  {
    "code": "1f38a",
    "name": "confetti ball",
    "category": "Smileys and emotions",
    "tags": [
      "confetti-ball"
    ]
  },
  {
    "code": "2764_fe0f",
    "name": "red heart",
    "category": "Smileys and emotions",
    "tags": [
      "red-heart"
    ]
  },
  {
    "code": "1f9e1",
    "name": "orange heart",
    "category": "Smileys and emotions",
    "tags": [
      "orange-heart"
    ]
  },
  {
    "code": "1f49b",
    "name": "yellow heart",
    "category": "Smileys and emotions",
    "tags": [
      "yellow-heart"
    ]
  },
  {
    "code": "1f49a",
    "name": "green heart",
    "category": "Smileys and emotions",
    "tags": [
      "green-heart"
    ]
  },
  {
    "code": "1fa75",
    "name": "light blue heart",
    "category": "Smileys and emotions",
    "tags": [
      "light-blue-heart"
    ]
  },
  {
    "code": "1f499",
    "name": "blue heart",
    "category": "Smileys and emotions",
    "tags": [
      "blue-heart"
    ]
  },
  {
    "code": "1f49c",
    "name": "purple heart",
    "category": "Smileys and emotions",
    "tags": [
      "purple-heart"
    ]
  },
  {
    "code": "1f90e",
    "name": "brown heart",
    "category": "Smileys and emotions",
    "tags": [
      "brown-heart"
    ]
  },
  {
    "code": "1f5a4",
    "name": "black heart",
    "category": "Smileys and emotions",
    "tags": [
      "black-heart"
    ]
  },
  {
    "code": "1fa76",
    "name": "grey heart",
    "category": "Smileys and emotions",
    "tags": [
      "grey-heart"
    ]
  },
  {
    "code": "1f90d",
    "name": "white heart",
    "category": "Smileys and emotions",
    "tags": [
      "white-heart"
    ]
  },
  {
    "code": "1fa77",
    "name": "pink heart",
    "category": "Smileys and emotions",
    "tags": [
      "pink-heart"
    ]
  },
  {
    "code": "1f498",
    "name": "cupid",
    "category": "Smileys and emotions",
    "tags": [
      "cupid"
    ]
  },
  {
    "code": "1f49d",
    "name": "gift heart",
    "category": "Smileys and emotions",
    "tags": [
      "gift-heart"
    ]
  },
  {
    "code": "1f496",
    "name": "sparkling heart",
    "category": "Smileys and emotions",
    "tags": [
      "sparkling-heart"
    ]
  },
  {
    "code": "1f497",
    "name": "heart grow",
    "category": "Smileys and emotions",
    "tags": [
      "heart-grow"
    ]
  },
  {
    "code": "1f493",
    "name": "beating heart",
    "category": "Smileys and emotions",
    "tags": [
      "beating-heart"
    ]
  },
  {
    "code": "1f49e",
    "name": "revolving hearts",
    "category": "Smileys and emotions",
    "tags": [
      "revolving-hearts"
    ]
  },
  {
    "code": "1f495",
    "name": "two hearts",
    "category": "Smileys and emotions",
    "tags": [
      "two-hearts"
    ]
  },
  {
    "code": "1f48c",
    "name": "love letter",
    "category": "Smileys and emotions",
    "tags": [
      "love-letter"
    ]
  },
  {
    "code": "1f49f",
    "name": "heart box",
    "category": "Smileys and emotions",
    "tags": [
      "heart-box"
    ]
  },
  {
    "code": "2665_fe0f",
    "name": "heart",
    "category": "Smileys and emotions",
    "tags": [
      "heart"
    ]
  },
  {
    "code": "2763_fe0f",
    "name": "heart exclamation point",
    "category": "Smileys and emotions",
    "tags": [
      "heart-exclamation-point"
    ]
  },
  {
    "code": "2764_fe0f_200d_1fa79",
    "name": "bandaged heart",
    "category": "Smileys and emotions",
    "tags": [
      "bandaged-heart"
    ]
  },
  {
    "code": "1f494",
    "name": "broken heart",
    "category": "Smileys and emotions",
    "tags": [
      "broken-heart"
    ]
  },
  {
    "code": "2764_fe0f_200d_1f525",
    "name": "fire heart",
    "category": "Smileys and emotions",
    "tags": [
      "fire-heart"
    ]
  },
  {
    "code": "1f48b",
    "name": "kiss",
    "category": "Smileys and emotions",
    "tags": [
      "kiss"
    ]
  },
  {
    "code": "1fac2",
    "name": "hugging",
    "category": "Smileys and emotions",
    "tags": [
      "hugging"
    ]
  },
  {
    "code": "1f5e3_fe0f",
    "name": "speaking head",
    "category": "Smileys and emotions",
    "tags": [
      "speaking-head"
    ]
  },
  {
    "code": "1f463",
    "name": "footprints",
    "category": "Smileys and emotions",
    "tags": [
      "footprints"
    ]
  },
  {
    "code": "1fac6",
    "name": "fingerprint",
    "category": "Smileys and emotions",
    "tags": [
      "fingerprint"
    ]
  },
  {
    "code": "1f9e0",
    "name": "brain",
    "category": "Smileys and emotions",
    "tags": [
      "brain"
    ]
  },
  {
    "code": "1fac0",
    "name": "anatomical heart",
    "category": "Smileys and emotions",
    "tags": [
      "anatomical-heart"
    ]
  },
  {
    "code": "1fa78",
    "name": "blood",
    "category": "Smileys and emotions",
    "tags": [
      "blood"
    ]
  },
  {
    "code": "1f9a0",
    "name": "microbe",
    "category": "Smileys and emotions",
    "tags": [
      "microbe",
      "virus"
    ]
  },
  {
    "code": "1f9b4",
    "name": "bone",
    "category": "Smileys and emotions",
    "tags": [
      "bone"
    ]
  },
  {
    "code": "1f440",
    "name": "eyes",
    "category": "Smileys and emotions",
    "tags": [
      "eyes"
    ]
  },
  {
    "code": "1f441_fe0f",
    "name": "eye",
    "category": "Smileys and emotions",
    "tags": [
      "eye"
    ]
  },
  {
    "code": "1fae6",
    "name": "biting lip",
    "category": "Smileys and emotions",
    "tags": [
      "biting-lip"
    ]
  },
  {
    "code": "1f443",
    "name": "nose",
    "category": "Smileys and emotions",
    "tags": [
      "nose"
    ]
  },
  {
    "code": "1f442",
    "name": "ear",
    "category": "Smileys and emotions",
    "tags": [
      "ear"
    ]
  },
  {
    "code": "1f9bb",
    "name": "hearing aid",
    "category": "Smileys and emotions",
    "tags": [
      "hearing-aid"
    ]
  },
  {
    "code": "1f9b6",
    "name": "foot",
    "category": "Smileys and emotions",
    "tags": [
      "foot"
    ]
  },
  {
    "code": "1f9b5",
    "name": "leg",
    "category": "Smileys and emotions",
    "tags": [
      "leg"
    ]
  },
  {
    "code": "1f9bf",
    "name": "leg mechanical",
    "category": "Smileys and emotions",
    "tags": [
      "leg-mechanical"
    ]
  },
  {
    "code": "1f9be",
    "name": "arm mechanical",
    "category": "Smileys and emotions",
    "tags": [
      "arm-mechanical"
    ]
  },
  {
    "code": "1f4aa",
    "name": "muscle",
    "category": "Smileys and emotions",
    "tags": [
      "muscle",
      "flex",
      "bicep",
      "strong"
    ]
  },
  {
    "code": "1f44f",
    "name": "clap",
    "category": "Smileys and emotions",
    "tags": [
      "clap"
    ]
  },
  {
    "code": "1f44d",
    "name": "thumbs up",
    "category": "Smileys and emotions",
    "tags": [
      "thumbs-up",
      "+1"
    ]
  },
  {
    "code": "1f44e",
    "name": "thumbs down",
    "category": "Smileys and emotions",
    "tags": [
      "thumbs-down"
    ]
  },
  {
    "code": "1faf6",
    "name": "heart hands",
    "category": "Smileys and emotions",
    "tags": [
      "heart-hands"
    ]
  },
  {
    "code": "1f64c",
    "name": "raising hands",
    "category": "Smileys and emotions",
    "tags": [
      "raising-hands",
      "hooray"
    ]
  },
  {
    "code": "1f450",
    "name": "open hands",
    "category": "Smileys and emotions",
    "tags": [
      "open-hands"
    ]
  },
  {
    "code": "1f932",
    "name": "palms up",
    "category": "Smileys and emotions",
    "tags": [
      "palms-up"
    ]
  },
  {
    "code": "1f91c",
    "name": "fist rightwards",
    "category": "Smileys and emotions",
    "tags": [
      "fist-rightwards"
    ]
  },
  {
    "code": "1f91b",
    "name": "fist leftwards",
    "category": "Smileys and emotions",
    "tags": [
      "fist-leftwards"
    ]
  },
  {
    "code": "270a",
    "name": "raised fist",
    "category": "Smileys and emotions",
    "tags": [
      "raised-fist"
    ]
  },
  {
    "code": "1f44a",
    "name": "fist",
    "category": "Smileys and emotions",
    "tags": [
      "fist",
      "bump"
    ]
  },
  {
    "code": "1faf3",
    "name": "palm down",
    "category": "Smileys and emotions",
    "tags": [
      "palm-down",
      "drop"
    ]
  },
  {
    "code": "1faf4",
    "name": "palm up",
    "category": "Smileys and emotions",
    "tags": [
      "palm-up",
      "throw"
    ]
  },
  {
    "code": "1faf1",
    "name": "rightwards hand",
    "category": "Smileys and emotions",
    "tags": [
      "rightwards-hand"
    ]
  },
  {
    "code": "1faf2",
    "name": "leftwards hand",
    "category": "Smileys and emotions",
    "tags": [
      "leftwards-hand"
    ]
  },
  {
    "code": "1faf8",
    "name": "push rightwards",
    "category": "Smileys and emotions",
    "tags": [
      "push-rightwards"
    ]
  },
  {
    "code": "1faf7",
    "name": "push leftwards",
    "category": "Smileys and emotions",
    "tags": [
      "push-leftwards"
    ]
  },
  {
    "code": "1f44b",
    "name": "wave",
    "category": "Smileys and emotions",
    "tags": [
      "wave"
    ]
  },
  {
    "code": "1f91a",
    "name": "back hand",
    "category": "Smileys and emotions",
    "tags": [
      "back-hand"
    ]
  },
  {
    "code": "1f590_fe0f",
    "name": "palm",
    "category": "Smileys and emotions",
    "tags": [
      "palm"
    ]
  },
  {
    "code": "270b",
    "name": "raised hand",
    "category": "Smileys and emotions",
    "tags": [
      "raised-hand"
    ]
  },
  {
    "code": "1f596",
    "name": "vulcan",
    "category": "Smileys and emotions",
    "tags": [
      "vulcan",
      "prosper",
      "spock"
    ]
  },
  {
    "code": "1f91f",
    "name": "love you gesture",
    "category": "Smileys and emotions",
    "tags": [
      "love-you-gesture"
    ]
  },
  {
    "code": "1f918",
    "name": "metal",
    "category": "Smileys and emotions",
    "tags": [
      "metal",
      "horns"
    ]
  },
  {
    "code": "270c_fe0f",
    "name": "victory",
    "category": "Smileys and emotions",
    "tags": [
      "victory",
      "v",
      "peace-hand"
    ]
  },
  {
    "code": "1f91e",
    "name": "crossed fingers",
    "category": "Smileys and emotions",
    "tags": [
      "crossed-fingers"
    ]
  },
  {
    "code": "1faf0",
    "name": "hand with index finger and thumb crossed",
    "category": "Smileys and emotions",
    "tags": [
      "hand-with-index-finger-and-thumb-crossed",
      "snap",
      "finger-heart"
    ]
  },
  {
    "code": "1f919",
    "name": "call me hand",
    "category": "Smileys and emotions",
    "tags": [
      "call-me-hand"
    ]
  },
  {
    "code": "1f90c",
    "name": "pinched fingers",
    "category": "Smileys and emotions",
    "tags": [
      "pinched-fingers"
    ]
  },
  {
    "code": "1f90f",
    "name": "pinch",
    "category": "Smileys and emotions",
    "tags": [
      "pinch"
    ]
  },
  {
    "code": "1f44c",
    "name": "ok",
    "category": "Smileys and emotions",
    "tags": [
      "ok"
    ]
  },
  {
    "code": "1faf5",
    "name": "pointing",
    "category": "Smileys and emotions",
    "tags": [
      "pointing"
    ]
  },
  {
    "code": "1f449",
    "name": "point right",
    "category": "Smileys and emotions",
    "tags": [
      "point-right"
    ]
  },
  {
    "code": "1f448",
    "name": "point left",
    "category": "Smileys and emotions",
    "tags": [
      "point-left"
    ]
  },
  {
    "code": "261d_fe0f",
    "name": "index finger",
    "category": "Smileys and emotions",
    "tags": [
      "index-finger"
    ]
  },
  {
    "code": "1f446",
    "name": "point up",
    "category": "Smileys and emotions",
    "tags": [
      "point-up"
    ]
  },
  {
    "code": "1f447",
    "name": "point down",
    "category": "Smileys and emotions",
    "tags": [
      "point-down"
    ]
  },
  {
    "code": "1f595",
    "name": "middle finger",
    "category": "Smileys and emotions",
    "tags": [
      "middle-finger"
    ]
  },
  {
    "code": "270d_fe0f",
    "name": "writing hand",
    "category": "Smileys and emotions",
    "tags": [
      "writing-hand"
    ]
  },
  {
    "code": "1f933",
    "name": "selfie",
    "category": "Smileys and emotions",
    "tags": [
      "selfie"
    ]
  },
  {
    "code": "1f64f",
    "name": "folded hands",
    "category": "Smileys and emotions",
    "tags": [
      "folded-hands",
      "please",
      "pray",
      "hope",
      "wish",
      "thank-you",
      "high-five"
    ]
  },
  {
    "code": "1f485",
    "name": "nail care",
    "category": "Smileys and emotions",
    "tags": [
      "nail-care"
    ]
  },
  {
    "code": "1f91d",
    "name": "handshake",
    "category": "Smileys and emotions",
    "tags": [
      "handshake"
    ]
  },
  {
    "code": "1fa82",
    "name": "parachute",
    "category": "People",
    "tags": [
      "parachute"
    ]
  },
  {
    "code": "1fac8",
    "name": "hairy creature",
    "category": "People",
    "tags": [
      "hairy-creature"
    ]
  },
  {
    "code": "1f483",
    "name": "dancer woman",
    "category": "People",
    "tags": [
      "dancer-woman"
    ]
  },
  {
    "code": "1f490",
    "name": "bouquet",
    "category": "Animals and nature",
    "tags": [
      "bouquet",
      "flowers"
    ]
  },
  {
    "code": "1f339",
    "name": "rose",
    "category": "Animals and nature",
    "tags": [
      "rose"
    ]
  },
  {
    "code": "1f940",
    "name": "wilted flower",
    "category": "Animals and nature",
    "tags": [
      "wilted-flower"
    ]
  },
  {
    "code": "1f337",
    "name": "tulip",
    "category": "Animals and nature",
    "tags": [
      "tulip"
    ]
  },
  {
    "code": "1fab7",
    "name": "lotus",
    "category": "Animals and nature",
    "tags": [
      "lotus"
    ]
  },
  {
    "code": "1f338",
    "name": "cherry blossom",
    "category": "Animals and nature",
    "tags": [
      "cherry-blossom"
    ]
  },
  {
    "code": "1fabb",
    "name": "hyacinth",
    "category": "Animals and nature",
    "tags": [
      "hyacinth"
    ]
  },
  {
    "code": "1f33c",
    "name": "blossom",
    "category": "Animals and nature",
    "tags": [
      "blossom"
    ]
  },
  {
    "code": "1f342",
    "name": "fallen leaf",
    "category": "Animals and nature",
    "tags": [
      "fallen-leaf"
    ]
  },
  {
    "code": "1f341",
    "name": "maple leaf",
    "category": "Animals and nature",
    "tags": [
      "maple-leaf"
    ]
  },
  {
    "code": "1f344",
    "name": "mushroom",
    "category": "Animals and nature",
    "tags": [
      "mushroom"
    ]
  },
  {
    "code": "1f33f",
    "name": "herb",
    "category": "Animals and nature",
    "tags": [
      "herb"
    ]
  },
  {
    "code": "1f331",
    "name": "plant",
    "category": "Animals and nature",
    "tags": [
      "plant",
      "seed"
    ]
  },
  {
    "code": "1f343",
    "name": "leaves",
    "category": "Animals and nature",
    "tags": [
      "leaves"
    ]
  },
  {
    "code": "1f340",
    "name": "luck",
    "category": "Animals and nature",
    "tags": [
      "luck",
      "four-leaf-clover"
    ]
  },
  {
    "code": "1f335",
    "name": "cactus",
    "category": "Animals and nature",
    "tags": [
      "cactus"
    ]
  },
  {
    "code": "1fabe",
    "name": "leafless tree",
    "category": "Animals and nature",
    "tags": [
      "leafless-tree"
    ]
  },
  {
    "code": "1f332",
    "name": "evergreen tree",
    "category": "Animals and nature",
    "tags": [
      "evergreen-tree"
    ]
  },
  {
    "code": "1faa8",
    "name": "rock",
    "category": "Animals and nature",
    "tags": [
      "rock"
    ]
  },
  {
    "code": "1f6d8",
    "name": "debris",
    "category": "Animals and nature",
    "tags": [
      "debris",
      "landslide"
    ]
  },
  {
    "code": "1f30b",
    "name": "volcano",
    "category": "Animals and nature",
    "tags": [
      "volcano"
    ]
  },
  {
    "code": "1f3de_fe0f",
    "name": "national park",
    "category": "Animals and nature",
    "tags": [
      "national-park"
    ]
  },
  {
    "code": "1f305",
    "name": "sunrise",
    "category": "Animals and nature",
    "tags": [
      "sunrise"
    ]
  },
  {
    "code": "1f304",
    "name": "sunrise over mountains",
    "category": "Animals and nature",
    "tags": [
      "sunrise-over-mountains"
    ]
  },
  {
    "code": "1f30a",
    "name": "ocean",
    "category": "Animals and nature",
    "tags": [
      "ocean"
    ]
  },
  {
    "code": "1f32c_fe0f",
    "name": "wind face",
    "category": "Animals and nature",
    "tags": [
      "wind-face"
    ]
  },
  {
    "code": "2744_fe0f",
    "name": "snowflake",
    "category": "Animals and nature",
    "tags": [
      "snowflake",
      "winter",
      "cold"
    ]
  },
  {
    "code": "1f300",
    "name": "cyclone",
    "category": "Animals and nature",
    "tags": [
      "cyclone"
    ]
  },
  {
    "code": "1f32a_fe0f",
    "name": "tornado",
    "category": "Animals and nature",
    "tags": [
      "tornado"
    ]
  },
  {
    "code": "1f308",
    "name": "rainbow",
    "category": "Animals and nature",
    "tags": [
      "rainbow"
    ]
  },
  {
    "code": "1f4a7",
    "name": "droplet",
    "category": "Animals and nature",
    "tags": [
      "droplet"
    ]
  },
  {
    "code": "2601_fe0f",
    "name": "cloud",
    "category": "Animals and nature",
    "tags": [
      "cloud"
    ]
  },
  {
    "code": "1f327_fe0f",
    "name": "rain cloud",
    "category": "Animals and nature",
    "tags": [
      "rain-cloud"
    ]
  },
  {
    "code": "1f329_fe0f",
    "name": "cloud with lightning",
    "category": "Animals and nature",
    "tags": [
      "cloud-with-lightning"
    ]
  },
  {
    "code": "26c5",
    "name": "partly sunny",
    "category": "Animals and nature",
    "tags": [
      "partly-sunny"
    ]
  },
  {
    "code": "1fa90",
    "name": "ringed planet",
    "category": "Animals and nature",
    "tags": [
      "ringed-planet"
    ]
  },
  {
    "code": "1f30d",
    "name": "globe showing Europe Africa",
    "category": "Animals and nature",
    "tags": [
      "globe-showing-Europe-Africa"
    ]
  },
  {
    "code": "1f30e",
    "name": "globe showing Americas",
    "category": "Animals and nature",
    "tags": [
      "globe-showing-Americas"
    ]
  },
  {
    "code": "1f30f",
    "name": "globe showing Asia Australia",
    "category": "Animals and nature",
    "tags": [
      "globe-showing-Asia-Australia"
    ]
  },
  {
    "code": "1f30c",
    "name": "milky way",
    "category": "Animals and nature",
    "tags": [
      "milky-way"
    ]
  },
  {
    "code": "2604_fe0f",
    "name": "comet",
    "category": "Animals and nature",
    "tags": [
      "comet"
    ]
  },
  {
    "code": "1f981",
    "name": "lion face",
    "category": "Animals and nature",
    "tags": [
      "lion-face"
    ]
  },
  {
    "code": "1f43a",
    "name": "wolf",
    "category": "Animals and nature",
    "tags": [
      "wolf"
    ]
  },
  {
    "code": "1f43b",
    "name": "bear face",
    "category": "Animals and nature",
    "tags": [
      "bear-face"
    ]
  },
  {
    "code": "1f43c",
    "name": "panda",
    "category": "Animals and nature",
    "tags": [
      "panda"
    ]
  },
  {
    "code": "1f98a",
    "name": "fox face",
    "category": "Animals and nature",
    "tags": [
      "fox-face"
    ]
  },
  {
    "code": "1f42e",
    "name": "cow face",
    "category": "Animals and nature",
    "tags": [
      "cow-face"
    ]
  },
  {
    "code": "1f984",
    "name": "unicorn",
    "category": "Animals and nature",
    "tags": [
      "unicorn"
    ]
  },
  {
    "code": "1f98e",
    "name": "lizard",
    "category": "Animals and nature",
    "tags": [
      "lizard"
    ]
  },
  {
    "code": "1f409",
    "name": "dragon",
    "category": "Animals and nature",
    "tags": [
      "dragon"
    ]
  },
  {
    "code": "1f996",
    "name": "t rex",
    "category": "Animals and nature",
    "tags": [
      "t-rex"
    ]
  },
  {
    "code": "1f995",
    "name": "dinosaur",
    "category": "Animals and nature",
    "tags": [
      "dinosaur"
    ]
  },
  {
    "code": "1f422",
    "name": "turtle",
    "category": "Animals and nature",
    "tags": [
      "turtle"
    ]
  },
  {
    "code": "1f40a",
    "name": "crocodile",
    "category": "Animals and nature",
    "tags": [
      "crocodile"
    ]
  },
  {
    "code": "1f40d",
    "name": "snake",
    "category": "Animals and nature",
    "tags": [
      "snake"
    ]
  },
  {
    "code": "1f438",
    "name": "frog",
    "category": "Animals and nature",
    "tags": [
      "frog"
    ]
  },
  {
    "code": "1f407",
    "name": "rabbit",
    "category": "Animals and nature",
    "tags": [
      "rabbit"
    ]
  },
  {
    "code": "1f400",
    "name": "rat",
    "category": "Animals and nature",
    "tags": [
      "rat"
    ]
  },
  {
    "code": "1f429",
    "name": "poodle",
    "category": "Animals and nature",
    "tags": [
      "poodle"
    ]
  },
  {
    "code": "1f415",
    "name": "dog",
    "category": "Animals and nature",
    "tags": [
      "dog"
    ]
  },
  {
    "code": "1f9ae",
    "name": "guide dog",
    "category": "Animals and nature",
    "tags": [
      "guide-dog"
    ]
  },
  {
    "code": "1f415_200d_1f9ba",
    "name": "service dog",
    "category": "Animals and nature",
    "tags": [
      "service-dog"
    ]
  },
  {
    "code": "1f416",
    "name": "pig",
    "category": "Animals and nature",
    "tags": [
      "pig"
    ]
  },
  {
    "code": "1f40e",
    "name": "racehorse",
    "category": "Animals and nature",
    "tags": [
      "racehorse"
    ]
  },
  {
    "code": "1facf",
    "name": "donkey",
    "category": "Animals and nature",
    "tags": [
      "donkey"
    ]
  },
  {
    "code": "1f402",
    "name": "ox",
    "category": "Animals and nature",
    "tags": [
      "ox"
    ]
  },
  {
    "code": "1f410",
    "name": "goat",
    "category": "Animals and nature",
    "tags": [
      "goat"
    ]
  },
  {
    "code": "1f9a5",
    "name": "sloth",
    "category": "Animals and nature",
    "tags": [
      "sloth"
    ]
  },
  {
    "code": "1f998",
    "name": "kangaroo",
    "category": "Animals and nature",
    "tags": [
      "kangaroo"
    ]
  },
  {
    "code": "1f405",
    "name": "tiger",
    "category": "Animals and nature",
    "tags": [
      "tiger"
    ]
  },
  {
    "code": "1f412",
    "name": "monkey",
    "category": "Animals and nature",
    "tags": [
      "monkey"
    ]
  },
  {
    "code": "1f98d",
    "name": "gorilla",
    "category": "Animals and nature",
    "tags": [
      "gorilla"
    ]
  },
  {
    "code": "1f9a7",
    "name": "orangutan",
    "category": "Animals and nature",
    "tags": [
      "orangutan"
    ]
  },
  {
    "code": "1f43f_fe0f",
    "name": "chipmunk",
    "category": "Animals and nature",
    "tags": [
      "chipmunk"
    ]
  },
  {
    "code": "1f99d",
    "name": "raccoon",
    "category": "Animals and nature",
    "tags": [
      "raccoon"
    ]
  },
  {
    "code": "1f994",
    "name": "hedgehog",
    "category": "Animals and nature",
    "tags": [
      "hedgehog"
    ]
  },
  {
    "code": "1f9a6",
    "name": "otter",
    "category": "Animals and nature",
    "tags": [
      "otter"
    ]
  },
  {
    "code": "1f987",
    "name": "bat",
    "category": "Animals and nature",
    "tags": [
      "bat"
    ]
  },
  {
    "code": "1f426",
    "name": "bird",
    "category": "Animals and nature",
    "tags": [
      "bird"
    ]
  },
  {
    "code": "1f426_200d_2b1b",
    "name": "black bird",
    "category": "Animals and nature",
    "tags": [
      "black-bird"
    ]
  },
  {
    "code": "1f413",
    "name": "rooster",
    "category": "Animals and nature",
    "tags": [
      "rooster"
    ]
  },
  {
    "code": "1f423",
    "name": "hatching chick",
    "category": "Animals and nature",
    "tags": [
      "hatching-chick"
    ]
  },
  {
    "code": "1f424",
    "name": "baby chick",
    "category": "Animals and nature",
    "tags": [
      "baby-chick"
    ]
  },
  {
    "code": "1f425",
    "name": "hatched chick",
    "category": "Animals and nature",
    "tags": [
      "hatched-chick"
    ]
  },
  {
    "code": "1f985",
    "name": "eagle",
    "category": "Animals and nature",
    "tags": [
      "eagle"
    ]
  },
  {
    "code": "1f989",
    "name": "owl",
    "category": "Animals and nature",
    "tags": [
      "owl"
    ]
  },
  {
    "code": "1f54a_fe0f",
    "name": "peace",
    "category": "Animals and nature",
    "tags": [
      "peace",
      "dove"
    ]
  },
  {
    "code": "1fabf",
    "name": "goose",
    "category": "Animals and nature",
    "tags": [
      "goose"
    ]
  },
  {
    "code": "1f9a9",
    "name": "flamingo",
    "category": "Animals and nature",
    "tags": [
      "flamingo"
    ]
  },
  {
    "code": "1f99a",
    "name": "peacock",
    "category": "Animals and nature",
    "tags": [
      "peacock"
    ]
  },
  {
    "code": "1f426_200d_1f525",
    "name": "phoenix",
    "category": "Animals and nature",
    "tags": [
      "phoenix"
    ]
  },
  {
    "code": "1f427",
    "name": "penguin",
    "category": "Animals and nature",
    "tags": [
      "penguin"
    ]
  },
  {
    "code": "1f9ad",
    "name": "seal",
    "category": "Animals and nature",
    "tags": [
      "seal"
    ]
  },
  {
    "code": "1f988",
    "name": "shark",
    "category": "Animals and nature",
    "tags": [
      "shark"
    ]
  },
  {
    "code": "1facd",
    "name": "orca",
    "category": "Animals and nature",
    "tags": [
      "orca"
    ]
  },
  {
    "code": "1f42c",
    "name": "dolphin",
    "category": "Animals and nature",
    "tags": [
      "dolphin"
    ]
  },
  {
    "code": "1f433",
    "name": "whale",
    "category": "Animals and nature",
    "tags": [
      "whale"
    ]
  },
  {
    "code": "1f41f",
    "name": "fish",
    "category": "Animals and nature",
    "tags": [
      "fish"
    ]
  },
  {
    "code": "1f421",
    "name": "blowfish",
    "category": "Animals and nature",
    "tags": [
      "blowfish"
    ]
  },
  {
    "code": "1f99e",
    "name": "lobster",
    "category": "Animals and nature",
    "tags": [
      "lobster"
    ]
  },
  {
    "code": "1f980",
    "name": "crab",
    "category": "Animals and nature",
    "tags": [
      "crab"
    ]
  },
  {
    "code": "1f419",
    "name": "octopus",
    "category": "Animals and nature",
    "tags": [
      "octopus"
    ]
  },
  {
    "code": "1fabc",
    "name": "jellyfish",
    "category": "Animals and nature",
    "tags": [
      "jellyfish"
    ]
  },
  {
    "code": "1fae7",
    "name": "bubbles",
    "category": "Animals and nature",
    "tags": [
      "bubbles"
    ]
  },
  {
    "code": "1f982",
    "name": "scorpion",
    "category": "Animals and nature",
    "tags": [
      "scorpion"
    ]
  },
  {
    "code": "1f577_fe0f",
    "name": "spider",
    "category": "Animals and nature",
    "tags": [
      "spider"
    ]
  },
  {
    "code": "1f40c",
    "name": "snail",
    "category": "Animals and nature",
    "tags": [
      "snail"
    ]
  },
  {
    "code": "1f41c",
    "name": "ant",
    "category": "Animals and nature",
    "tags": [
      "ant"
    ]
  },
  {
    "code": "1f997",
    "name": "cricket",
    "category": "Animals and nature",
    "tags": [
      "cricket"
    ]
  },
  {
    "code": "1f99f",
    "name": "mosquito",
    "category": "Animals and nature",
    "tags": [
      "mosquito"
    ]
  },
  {
    "code": "1fab3",
    "name": "cockroach",
    "category": "Animals and nature",
    "tags": [
      "cockroach"
    ]
  },
  {
    "code": "1fab0",
    "name": "fly",
    "category": "Animals and nature",
    "tags": [
      "fly"
    ]
  },
  {
    "code": "1f41d",
    "name": "bee",
    "category": "Animals and nature",
    "tags": [
      "bee"
    ]
  },
  {
    "code": "1f41e",
    "name": "lady bug",
    "category": "Animals and nature",
    "tags": [
      "lady-bug"
    ]
  },
  {
    "code": "1f98b",
    "name": "butterfly",
    "category": "Animals and nature",
    "tags": [
      "butterfly"
    ]
  },
  {
    "code": "1f41b",
    "name": "bug",
    "category": "Animals and nature",
    "tags": [
      "bug"
    ]
  },
  {
    "code": "1fab1",
    "name": "worm",
    "category": "Animals and nature",
    "tags": [
      "worm"
    ]
  },
  {
    "code": "1f43e",
    "name": "paw prints",
    "category": "Animals and nature",
    "tags": [
      "paw prints"
    ]
  },
  {
    "code": "1f353",
    "name": "strawberry",
    "category": "Food and drink",
    "tags": [
      "strawberry"
    ]
  },
  {
    "code": "1f352",
    "name": "cherries",
    "category": "Food and drink",
    "tags": [
      "cherries"
    ]
  },
  {
    "code": "1f34e",
    "name": "red apple",
    "category": "Food and drink",
    "tags": [
      "red-apple"
    ]
  },
  {
    "code": "1f345",
    "name": "tomato",
    "category": "Food and drink",
    "tags": [
      "tomato"
    ]
  },
  {
    "code": "1f349",
    "name": "watermelon",
    "category": "Food and drink",
    "tags": [
      "watermelon"
    ]
  },
  {
    "code": "1f34a",
    "name": "tangerine",
    "category": "Food and drink",
    "tags": [
      "tangerine",
      "orange",
      "mandarin"
    ]
  },
  {
    "code": "1f955",
    "name": "carrot",
    "category": "Food and drink",
    "tags": [
      "carrot"
    ]
  },
  {
    "code": "1f96d",
    "name": "mango",
    "category": "Food and drink",
    "tags": [
      "mango"
    ]
  },
  {
    "code": "1f34d",
    "name": "pineapple",
    "category": "Food and drink",
    "tags": [
      "pineapple"
    ]
  },
  {
    "code": "1f33d",
    "name": "ear of corn",
    "category": "Food and drink",
    "tags": [
      "ear-of-corn"
    ]
  },
  {
    "code": "1f34b",
    "name": "lemon",
    "category": "Food and drink",
    "tags": [
      "lemon"
    ]
  },
  {
    "code": "1f348",
    "name": "melon",
    "category": "Food and drink",
    "tags": [
      "melon"
    ]
  },
  {
    "code": "1f350",
    "name": "pear",
    "category": "Food and drink",
    "tags": [
      "pear"
    ]
  },
  {
    "code": "1fadb",
    "name": "pea pod",
    "category": "Food and drink",
    "tags": [
      "pea-pod"
    ]
  },
  {
    "code": "1f96c",
    "name": "leafy green",
    "category": "Food and drink",
    "tags": [
      "leafy-green"
    ]
  },
  {
    "code": "1fad1",
    "name": "bell pepper",
    "category": "Food and drink",
    "tags": [
      "bell-pepper"
    ]
  },
  {
    "code": "1f95d",
    "name": "kiwi fruit",
    "category": "Food and drink",
    "tags": [
      "kiwi-fruit"
    ]
  },
  {
    "code": "1f951",
    "name": "avocado",
    "category": "Food and drink",
    "tags": [
      "avocado"
    ]
  },
  {
    "code": "1f966",
    "name": "broccoli",
    "category": "Food and drink",
    "tags": [
      "broccoli"
    ]
  },
  {
    "code": "1f952",
    "name": "cucumber",
    "category": "Food and drink",
    "tags": [
      "cucumber"
    ]
  },
  {
    "code": "1fad0",
    "name": "blueberries",
    "category": "Food and drink",
    "tags": [
      "blueberries"
    ]
  },
  {
    "code": "1f347",
    "name": "grapes",
    "category": "Food and drink",
    "tags": [
      "grapes"
    ]
  },
  {
    "code": "1fadc",
    "name": "root vegetable",
    "category": "Food and drink",
    "tags": [
      "root-vegetable",
      "beet",
      "turnip"
    ]
  },
  {
    "code": "1f954",
    "name": "potato",
    "category": "Food and drink",
    "tags": [
      "potato"
    ]
  },
  {
    "code": "1f9c5",
    "name": "onion",
    "category": "Food and drink",
    "tags": [
      "onion"
    ]
  },
  {
    "code": "1fada",
    "name": "ginger",
    "category": "Food and drink",
    "tags": [
      "ginger"
    ]
  },
  {
    "code": "1f9c4",
    "name": "garlic",
    "category": "Food and drink",
    "tags": [
      "garlic"
    ]
  },
  {
    "code": "1fad8",
    "name": "beans",
    "category": "Food and drink",
    "tags": [
      "beans"
    ]
  },
  {
    "code": "1f35e",
    "name": "bread",
    "category": "Food and drink",
    "tags": [
      "bread"
    ]
  },
  {
    "code": "1f95e",
    "name": "pancakes",
    "category": "Food and drink",
    "tags": [
      "pancakes"
    ]
  },
  {
    "code": "1f373",
    "name": "cooking",
    "category": "Food and drink",
    "tags": [
      "cooking"
    ]
  },
  {
    "code": "1f9c0",
    "name": "cheese wedge",
    "category": "Food and drink",
    "tags": [
      "cheese-wedge"
    ]
  },
  {
    "code": "1f953",
    "name": "bacon",
    "category": "Food and drink",
    "tags": [
      "bacon"
    ]
  },
  {
    "code": "1f357",
    "name": "poultry leg",
    "category": "Food and drink",
    "tags": [
      "poultry-leg"
    ]
  },
  {
    "code": "1f354",
    "name": "hamburger",
    "category": "Food and drink",
    "tags": [
      "hamburger"
    ]
  },
  {
    "code": "1f32d",
    "name": "hot dog",
    "category": "Food and drink",
    "tags": [
      "hot-dog"
    ]
  },
  {
    "code": "1f968",
    "name": "pretzel",
    "category": "Food and drink",
    "tags": [
      "pretzel"
    ]
  },
  {
    "code": "1f355",
    "name": "pizza",
    "category": "Food and drink",
    "tags": [
      "pizza"
    ]
  },
  {
    "code": "1f32e",
    "name": "taco",
    "category": "Food and drink",
    "tags": [
      "taco"
    ]
  },
  {
    "code": "1f32f",
    "name": "burrito",
    "category": "Food and drink",
    "tags": [
      "burrito"
    ]
  },
  {
    "code": "1f35d",
    "name": "spaghetti",
    "category": "Food and drink",
    "tags": [
      "spaghetti"
    ]
  },
  {
    "code": "1f957",
    "name": "green salad",
    "category": "Food and drink",
    "tags": [
      "green-salad"
    ]
  },
  {
    "code": "1f35c",
    "name": "steaming bowl",
    "category": "Food and drink",
    "tags": [
      "steaming-bowl"
    ]
  },
  {
    "code": "1f362",
    "name": "oden",
    "category": "Food and drink",
    "tags": [
      "oden"
    ]
  },
  {
    "code": "1f361",
    "name": "dango",
    "category": "Food and drink",
    "tags": [
      "dango"
    ]
  },
  {
    "code": "1f368",
    "name": "ice cream",
    "category": "Food and drink",
    "tags": [
      "ice-cream"
    ]
  },
  {
    "code": "1f366",
    "name": "soft ice cream",
    "category": "Food and drink",
    "tags": [
      "soft-ice-cream"
    ]
  },
  {
    "code": "1f967",
    "name": "pie",
    "category": "Food and drink",
    "tags": [
      "pie"
    ]
  },
  {
    "code": "1f369",
    "name": "doughnut",
    "category": "Food and drink",
    "tags": [
      "doughnut"
    ]
  },
  {
    "code": "1f36a",
    "name": "cookie",
    "category": "Food and drink",
    "tags": [
      "cookie"
    ]
  },
  {
    "code": "1f9c2",
    "name": "salt",
    "category": "Food and drink",
    "tags": [
      "salt"
    ]
  },
  {
    "code": "1f37f",
    "name": "popcorn",
    "category": "Food and drink",
    "tags": [
      "popcorn"
    ]
  },
  {
    "code": "1f9cb",
    "name": "bubble tea",
    "category": "Food and drink",
    "tags": [
      "bubble-tea",
      "milk-tea"
    ]
  },
  {
    "code": "1f9c3",
    "name": "beverage box",
    "category": "Food and drink",
    "tags": [
      "beverage-box"
    ]
  },
  {
    "code": "1f37c",
    "name": "baby bottle",
    "category": "Food and drink",
    "tags": [
      "baby-bottle"
    ]
  },
  {
    "code": "1f375",
    "name": "teacup without handle",
    "category": "Food and drink",
    "tags": [
      "teacup-without-handle"
    ]
  },
  {
    "code": "2615",
    "name": "hot beverage",
    "category": "Food and drink",
    "tags": [
      "hot-beverage"
    ]
  },
  {
    "code": "1fad6",
    "name": "teapot",
    "category": "Food and drink",
    "tags": [
      "teapot"
    ]
  },
  {
    "code": "1f9c9",
    "name": "mate",
    "category": "Food and drink",
    "tags": [
      "mate"
    ]
  },
  {
    "code": "1f37b",
    "name": "clinking beer mugs",
    "category": "Food and drink",
    "tags": [
      "clinking-beer-mugs"
    ]
  },
  {
    "code": "1f942",
    "name": "clinking glasses",
    "category": "Food and drink",
    "tags": [
      "clinking-glasses"
    ]
  },
  {
    "code": "1f37e",
    "name": "bottle with popping cork",
    "category": "Food and drink",
    "tags": [
      "bottle-with-popping-cork"
    ]
  },
  {
    "code": "1f377",
    "name": "wine glass",
    "category": "Food and drink",
    "tags": [
      "wine-glass"
    ]
  },
  {
    "code": "1fad7",
    "name": "pour",
    "category": "Food and drink",
    "tags": [
      "pour"
    ]
  },
  {
    "code": "1f379",
    "name": "tropical drink",
    "category": "Food and drink",
    "tags": [
      "tropical-drink"
    ]
  },
  {
    "code": "1f962",
    "name": "chopsticks",
    "category": "Food and drink",
    "tags": [
      "chopsticks"
    ]
  },
  {
    "code": "1f37d_fe0f",
    "name": "fork and knife with plate",
    "category": "Food and drink",
    "tags": [
      "fork-and-knife-with-plate"
    ]
  },
  {
    "code": "1f6d1",
    "name": "stop sign",
    "category": "Travel and places",
    "tags": [
      "stop-sign"
    ]
  },
  {
    "code": "1f6a7",
    "name": "construction",
    "category": "Travel and places",
    "tags": [
      "construction"
    ]
  },
  {
    "code": "1f6a8",
    "name": "police car light",
    "category": "Travel and places",
    "tags": [
      "police-car-light"
    ]
  },
  {
    "code": "26fd",
    "name": "fuel pump",
    "category": "Travel and places",
    "tags": [
      "fuel-pump"
    ]
  },
  {
    "code": "1f6df",
    "name": "ring buoy",
    "category": "Travel and places",
    "tags": [
      "ring-buoy"
    ]
  },
  {
    "code": "2693",
    "name": "anchor",
    "category": "Travel and places",
    "tags": [
      "anchor"
    ]
  },
  {
    "code": "1f6a6",
    "name": "vertical traffic light",
    "category": "Travel and places",
    "tags": [
      "vertical-traffic-light"
    ]
  },
  {
    "code": "1f6b2",
    "name": "bicycle",
    "category": "Travel and places",
    "tags": [
      "bicycle"
    ]
  },
  {
    "code": "1f3cd_fe0f",
    "name": "motorcycle",
    "category": "Travel and places",
    "tags": [
      "motorcycle"
    ]
  },
  {
    "code": "1f697",
    "name": "automobile",
    "category": "Travel and places",
    "tags": [
      "automobile"
    ]
  },
  {
    "code": "1f69a",
    "name": "delivery truck",
    "category": "Travel and places",
    "tags": [
      "delivery-truck"
    ]
  },
  {
    "code": "1f69c",
    "name": "tractor",
    "category": "Travel and places",
    "tags": [
      "tractor"
    ]
  },
  {
    "code": "1f3ce_fe0f",
    "name": "racing car",
    "category": "Travel and places",
    "tags": [
      "racing-car"
    ]
  },
  {
    "code": "1f695",
    "name": "taxi",
    "category": "Travel and places",
    "tags": [
      "taxi"
    ]
  },
  {
    "code": "1f68c",
    "name": "bus",
    "category": "Travel and places",
    "tags": [
      "bus"
    ]
  },
  {
    "code": "1f682",
    "name": "locomotive",
    "category": "Travel and places",
    "tags": [
      "locomotive"
    ]
  },
  {
    "code": "26f5",
    "name": "sailboat",
    "category": "Travel and places",
    "tags": [
      "sailboat"
    ]
  },
  {
    "code": "1f6f6",
    "name": "canoe",
    "category": "Travel and places",
    "tags": [
      "canoe"
    ]
  },
  {
    "code": "1f6f8",
    "name": "flying saucer",
    "category": "Travel and places",
    "tags": [
      "flying-saucer"
    ]
  },
  {
    "code": "1f680",
    "name": "rocket",
    "category": "Travel and places",
    "tags": [
      "rocket"
    ]
  },
  {
    "code": "2708_fe0f",
    "name": "airplane",
    "category": "Travel and places",
    "tags": [
      "airplane"
    ]
  },
  {
    "code": "1f6eb",
    "name": "airplane departure",
    "category": "Travel and places",
    "tags": [
      "airplane-departure"
    ]
  },
  {
    "code": "1f6ec",
    "name": "airplane arrival",
    "category": "Travel and places",
    "tags": [
      "airplane-arrival"
    ]
  },
  {
    "code": "1f3a2",
    "name": "roller coaster",
    "category": "Travel and places",
    "tags": [
      "roller-coaster"
    ]
  },
  {
    "code": "1f3a1",
    "name": "ferris wheel",
    "category": "Travel and places",
    "tags": [
      "ferris-wheel"
    ]
  },
  {
    "code": "1f3a0",
    "name": "carousel horse",
    "category": "Travel and places",
    "tags": [
      "carousel-horse"
    ]
  },
  {
    "code": "1f5ff",
    "name": "moai",
    "category": "Travel and places",
    "tags": [
      "moai"
    ]
  },
  {
    "code": "1f3da_fe0f",
    "name": "derelict house",
    "category": "Travel and places",
    "tags": [
      "derelict-house"
    ]
  },
  {
    "code": "1f3e0",
    "name": "house",
    "category": "Travel and places",
    "tags": [
      "house"
    ]
  },
  {
    "code": "1f3d5_fe0f",
    "name": "camping",
    "category": "Travel and places",
    "tags": [
      "camping"
    ]
  },
  {
    "code": "1f307",
    "name": "sunset",
    "category": "Travel and places",
    "tags": [
      "sunset"
    ]
  },
  {
    "code": "1f388",
    "name": "balloon",
    "category": "Activities and events",
    "tags": [
      "balloon"
    ]
  },
  {
    "code": "1f382",
    "name": "birthday cake",
    "category": "Activities and events",
    "tags": [
      "birthday-cake"
    ]
  },
  {
    "code": "1f381",
    "name": "wrapped gift",
    "category": "Activities and events",
    "tags": [
      "wrapped-gift"
    ]
  },
  {
    "code": "1f386",
    "name": "fireworks",
    "category": "Activities and events",
    "tags": [
      "fireworks"
    ]
  },
  {
    "code": "1fa94",
    "name": "diya lamp",
    "category": "Activities and events",
    "tags": [
      "diya-lamp"
    ]
  },
  {
    "code": "1fa85",
    "name": "piñata",
    "category": "Activities and events",
    "tags": [
      "piñata"
    ]
  },
  {
    "code": "1faa9",
    "name": "mirror ball",
    "category": "Activities and events",
    "tags": [
      "mirror-ball",
      "disco-ball"
    ]
  },
  {
    "code": "1f947",
    "name": "gold medal",
    "category": "Activities and events",
    "tags": [
      "gold-medal",
      "1st-place-medal"
    ]
  },
  {
    "code": "1f948",
    "name": "silver medal",
    "category": "Activities and events",
    "tags": [
      "silver-medal",
      "2nd-place-medal"
    ]
  },
  {
    "code": "1f949",
    "name": "bronze medal",
    "category": "Activities and events",
    "tags": [
      "bronze-medal",
      "3rd-place-medal"
    ]
  },
  {
    "code": "1f3c6",
    "name": "trophy",
    "category": "Activities and events",
    "tags": [
      "trophy"
    ]
  },
  {
    "code": "26bd",
    "name": "soccer ball",
    "category": "Activities and events",
    "tags": [
      "soccer-ball"
    ]
  },
  {
    "code": "26be",
    "name": "baseball",
    "category": "Activities and events",
    "tags": [
      "baseball"
    ]
  },
  {
    "code": "1f94e",
    "name": "softball",
    "category": "Activities and events",
    "tags": [
      "softball"
    ]
  },
  {
    "code": "1f3c0",
    "name": "basketball",
    "category": "Activities and events",
    "tags": [
      "basketball"
    ]
  },
  {
    "code": "1f3c9",
    "name": "rugby football",
    "category": "Activities and events",
    "tags": [
      "rugby-football"
    ]
  },
  {
    "code": "1f3be",
    "name": "tennis",
    "category": "Activities and events",
    "tags": [
      "tennis"
    ]
  },
  {
    "code": "1f3f8",
    "name": "badminton",
    "category": "Activities and events",
    "tags": [
      "badminton"
    ]
  },
  {
    "code": "1f94d",
    "name": "lacrosse",
    "category": "Activities and events",
    "tags": [
      "lacrosse"
    ]
  },
  {
    "code": "1f3cf",
    "name": "cricket game",
    "category": "Activities and events",
    "tags": [
      "cricket-game"
    ]
  },
  {
    "code": "1f3d1",
    "name": "field hockey",
    "category": "Activities and events",
    "tags": [
      "field-hockey"
    ]
  },
  {
    "code": "1f3d2",
    "name": "ice hockey",
    "category": "Activities and events",
    "tags": [
      "ice-hockey"
    ]
  },
  {
    "code": "1f3bf",
    "name": "skis",
    "category": "Activities and events",
    "tags": [
      "skis"
    ]
  },
  {
    "code": "26f8_fe0f",
    "name": "ice skate",
    "category": "Activities and events",
    "tags": [
      "ice-skate"
    ]
  },
  {
    "code": "1f6fc",
    "name": "roller skates",
    "category": "Activities and events",
    "tags": [
      "roller-skates"
    ]
  },
  {
    "code": "1fa70",
    "name": "ballet shoes",
    "category": "Activities and events",
    "tags": [
      "ballet-shoes"
    ]
  },
  {
    "code": "1f6f9",
    "name": "skateboard",
    "category": "Activities and events",
    "tags": [
      "skateboard"
    ]
  },
  {
    "code": "26f3",
    "name": "flag in hole",
    "category": "Activities and events",
    "tags": [
      "flag-in-hole"
    ]
  },
  {
    "code": "1f3af",
    "name": "direct hit",
    "category": "Activities and events",
    "tags": [
      "direct-hit",
      "target"
    ]
  },
  {
    "code": "1f94f",
    "name": "flying disc",
    "category": "Activities and events",
    "tags": [
      "flying-disc"
    ]
  },
  {
    "code": "1fa83",
    "name": "boomerang",
    "category": "Activities and events",
    "tags": [
      "boomerang"
    ]
  },
  {
    "code": "1fa81",
    "name": "kite",
    "category": "Activities and events",
    "tags": [
      "kite"
    ]
  },
  {
    "code": "1f3a3",
    "name": "fishing pole",
    "category": "Activities and events",
    "tags": [
      "fishing-pole"
    ]
  },
  {
    "code": "1f94b",
    "name": "martial arts uniform",
    "category": "Activities and events",
    "tags": [
      "martial-arts-uniform"
    ]
  },
  {
    "code": "1f3b1",
    "name": "8 ball",
    "category": "Activities and events",
    "tags": [
      "8-ball"
    ]
  },
  {
    "code": "1f3d3",
    "name": "ping pong",
    "category": "Activities and events",
    "tags": [
      "ping-pong"
    ]
  },
  {
    "code": "1f3b3",
    "name": "bowling",
    "category": "Activities and events",
    "tags": [
      "bowling"
    ]
  },
  {
    "code": "265f_fe0f",
    "name": "chess pawn",
    "category": "Activities and events",
    "tags": [
      "chess-pawn"
    ]
  },
  {
    "code": "1f3b2",
    "name": "die",
    "category": "Activities and events",
    "tags": [
      "die"
    ]
  },
  {
    "code": "1f3b0",
    "name": "slot machine",
    "category": "Activities and events",
    "tags": [
      "slot-machine"
    ]
  },
  {
    "code": "1fa84",
    "name": "wand",
    "category": "Activities and events",
    "tags": [
      "wand"
    ]
  },
  {
    "code": "1f4f7",
    "name": "camera",
    "category": "Activities and events",
    "tags": [
      "camera"
    ]
  },
  {
    "code": "1f4f8",
    "name": "camera flash",
    "category": "Activities and events",
    "tags": [
      "camera-flash"
    ]
  },
  {
    "code": "1fadf",
    "name": "splatter",
    "category": "Activities and events",
    "tags": [
      "splatter"
    ]
  },
  {
    "code": "1f3b7",
    "name": "saxophone",
    "category": "Activities and events",
    "tags": [
      "saxophone"
    ]
  },
  {
    "code": "1f3ba",
    "name": "trumpet",
    "category": "Activities and events",
    "tags": [
      "trumpet"
    ]
  },
  {
    "code": "1fa8a",
    "name": "trombone",
    "category": "Activities and events",
    "tags": [
      "trombone"
    ]
  },
  {
    "code": "1f3b8",
    "name": "guitar",
    "category": "Activities and events",
    "tags": [
      "guitar"
    ]
  },
  {
    "code": "1fa95",
    "name": "banjo",
    "category": "Activities and events",
    "tags": [
      "banjo"
    ]
  },
  {
    "code": "1f3bb",
    "name": "violin",
    "category": "Activities and events",
    "tags": [
      "violin"
    ]
  },
  {
    "code": "1fa89",
    "name": "harp",
    "category": "Activities and events",
    "tags": [
      "harp"
    ]
  },
  {
    "code": "1f941",
    "name": "drum",
    "category": "Activities and events",
    "tags": [
      "drum"
    ]
  },
  {
    "code": "1fa87",
    "name": "maracas",
    "category": "Activities and events",
    "tags": [
      "maracas"
    ]
  },
  {
    "code": "1f4fa",
    "name": "television",
    "category": "Activities and events",
    "tags": [
      "television"
    ]
  },
  {
    "code": "1f39e_fe0f",
    "name": "film",
    "category": "Activities and events",
    "tags": [
      "film"
    ]
  },
  {
    "code": "1f3ac",
    "name": "clapper",
    "category": "Activities and events",
    "tags": [
      "clapper"
    ]
  },
  {
    "code": "1f3ad",
    "name": "performing arts",
    "category": "Activities and events",
    "tags": [
      "performing-arts"
    ]
  },
  {
    "code": "1f39f_fe0f",
    "name": "admission tickets",
    "category": "Activities and events",
    "tags": [
      "admission-tickets"
    ]
  },
  {
    "code": "1f4df",
    "name": "pager",
    "category": "Objects",
    "tags": [
      "pager"
    ]
  },
  {
    "code": "1f50c",
    "name": "electric plug",
    "category": "Objects",
    "tags": [
      "electric-plug"
    ]
  },
  {
    "code": "1f50b",
    "name": "battery full",
    "category": "Objects",
    "tags": [
      "battery-full"
    ]
  },
  {
    "code": "1faab",
    "name": "battery low",
    "category": "Objects",
    "tags": [
      "battery-low"
    ]
  },
  {
    "code": "1f4bf",
    "name": "optical disk",
    "category": "Objects",
    "tags": [
      "optical-disk"
    ]
  },
  {
    "code": "1f4bb",
    "name": "laptop computer",
    "category": "Objects",
    "tags": [
      "laptop-computer"
    ]
  },
  {
    "code": "1f5a8_fe0f",
    "name": "printer",
    "category": "Objects",
    "tags": [
      "printer"
    ]
  },
  {
    "code": "1fa8e",
    "name": "treasure",
    "category": "Objects",
    "tags": [
      "treasure"
    ]
  },
  {
    "code": "1fa99",
    "name": "coin",
    "category": "Objects",
    "tags": [
      "coin"
    ]
  },
  {
    "code": "1f48e",
    "name": "gem stone",
    "category": "Objects",
    "tags": [
      "gem-stone"
    ]
  },
  {
    "code": "1f4b8",
    "name": "money with wings",
    "category": "Objects",
    "tags": [
      "money-with-wings"
    ]
  },
  {
    "code": "2696_fe0f",
    "name": "balance scale",
    "category": "Objects",
    "tags": [
      "balance-scale"
    ]
  },
  {
    "code": "1f6d2",
    "name": "shopping cart",
    "category": "Objects",
    "tags": [
      "shopping-cart"
    ]
  },
  {
    "code": "1f4a1",
    "name": "light bulb",
    "category": "Objects",
    "tags": [
      "light-bulb"
    ]
  },
  {
    "code": "1f9f9",
    "name": "broom",
    "category": "Objects",
    "tags": [
      "broom"
    ]
  },
  {
    "code": "1f9e6",
    "name": "socks",
    "category": "Objects",
    "tags": [
      "socks"
    ]
  },
  {
    "code": "1f393",
    "name": "graduation cap",
    "category": "Objects",
    "tags": [
      "graduation-cap"
    ]
  },
  {
    "code": "1f451",
    "name": "crown",
    "category": "Objects",
    "tags": [
      "crown"
    ]
  },
  {
    "code": "1f48d",
    "name": "ring",
    "category": "Objects",
    "tags": [
      "ring"
    ]
  },
  {
    "code": "1faad",
    "name": "fan",
    "category": "Objects",
    "tags": [
      "fan"
    ]
  },
  {
    "code": "2602_fe0f",
    "name": "umbrella",
    "category": "Objects",
    "tags": [
      "umbrella"
    ]
  },
  {
    "code": "1f460",
    "name": "high heeled shoe",
    "category": "Objects",
    "tags": [
      "high-heeled-shoe"
    ]
  },
  {
    "code": "1f45f",
    "name": "running shoe",
    "category": "Objects",
    "tags": [
      "running-shoe"
    ]
  },
  {
    "code": "1f321_fe0f",
    "name": "thermometer",
    "category": "Objects",
    "tags": [
      "thermometer"
    ]
  },
  {
    "code": "1fa7a",
    "name": "stethoscope",
    "category": "Objects",
    "tags": [
      "stethoscope"
    ]
  },
  {
    "code": "1f6e0_fe0f",
    "name": "hammer and wrench",
    "category": "Objects",
    "tags": [
      "hammer-and-wrench"
    ]
  },
  {
    "code": "1fa8f",
    "name": "shovel",
    "category": "Objects",
    "tags": [
      "shovel",
      "dig"
    ]
  },
  {
    "code": "2699_fe0f",
    "name": "gear",
    "category": "Objects",
    "tags": [
      "gear"
    ]
  },
  {
    "code": "26d3_fe0f_200d_1f4a5",
    "name": "broken chain",
    "category": "Objects",
    "tags": [
      "broken-chain"
    ]
  },
  {
    "code": "26d3_fe0f",
    "name": "chains",
    "category": "Objects",
    "tags": [
      "chains"
    ]
  },
  {
    "code": "1f587_fe0f",
    "name": "linked paperclips",
    "category": "Objects",
    "tags": [
      "linked-paperclips"
    ]
  },
  {
    "code": "2702_fe0f",
    "name": "scissors",
    "category": "Objects",
    "tags": [
      "scissors"
    ]
  },
  {
    "code": "270f_fe0f",
    "name": "pencil",
    "category": "Objects",
    "tags": [
      "pencil"
    ]
  },
  {
    "code": "1f4da",
    "name": "books",
    "category": "Objects",
    "tags": [
      "books"
    ]
  },
  {
    "code": "1f4ca",
    "name": "bar chart",
    "category": "Objects",
    "tags": [
      "bar-chart"
    ]
  },
  {
    "code": "1f4c8",
    "name": "chart increasing",
    "category": "Objects",
    "tags": [
      "chart-increasing"
    ]
  },
  {
    "code": "1f4c9",
    "name": "chart decreasing",
    "category": "Objects",
    "tags": [
      "chart-decreasing"
    ]
  },
  {
    "code": "1f5d1_fe0f",
    "name": "wastebasket",
    "category": "Objects",
    "tags": [
      "wastebasket"
    ]
  },
  {
    "code": "1f4e6",
    "name": "package",
    "category": "Objects",
    "tags": [
      "package"
    ]
  },
  {
    "code": "1f5f3_fe0f",
    "name": "ballot box",
    "category": "Objects",
    "tags": [
      "ballot-box"
    ]
  },
  {
    "code": "23f0",
    "name": "alarm clock",
    "category": "Objects",
    "tags": [
      "alarm-clock"
    ]
  },
  {
    "code": "231b",
    "name": "hourglass done",
    "category": "Objects",
    "tags": [
      "hourglass-done"
    ]
  },
  {
    "code": "23f3",
    "name": "hourglass not done",
    "category": "Objects",
    "tags": [
      "hourglass-not-done"
    ]
  },
  {
    "code": "1f6ce_fe0f",
    "name": "bellhop bell",
    "category": "Objects",
    "tags": [
      "bellhop-bell"
    ]
  },
  {
    "code": "1f514",
    "name": "bell",
    "category": "Objects",
    "tags": [
      "bell"
    ]
  },
  {
    "code": "1f4e3",
    "name": "megaphone",
    "category": "Objects",
    "tags": [
      "megaphone"
    ]
  },
  {
    "code": "1f50e",
    "name": "magnifying glass tilted right",
    "category": "Objects",
    "tags": [
      "magnifying-glass-tilted-right"
    ]
  },
  {
    "code": "1f52e",
    "name": "crystal ball",
    "category": "Objects",
    "tags": [
      "crystal-ball"
    ]
  },
  {
    "code": "1f4a3",
    "name": "bomb",
    "category": "Objects",
    "tags": [
      "bomb"
    ]
  },
  {
    "code": "1faa4",
    "name": "mouse trap",
    "category": "Objects",
    "tags": [
      "mouse-trap"
    ]
  },
  {
    "code": "1f512",
    "name": "locked",
    "category": "Objects",
    "tags": [
      "locked"
    ]
  },
  {
    "code": "2660_fe0f",
    "name": "spade",
    "category": "Symbols",
    "tags": [
      "spade"
    ]
  },
  {
    "code": "2648",
    "name": "Aries",
    "category": "Symbols",
    "tags": [
      "Aries"
    ]
  },
  {
    "code": "2649",
    "name": "Taurus",
    "category": "Symbols",
    "tags": [
      "Taurus"
    ]
  },
  {
    "code": "264a",
    "name": "Gemini",
    "category": "Symbols",
    "tags": [
      "Gemini"
    ]
  },
  {
    "code": "264b",
    "name": "Cancer",
    "category": "Symbols",
    "tags": [
      "Cancer"
    ]
  },
  {
    "code": "264c",
    "name": "Leo",
    "category": "Symbols",
    "tags": [
      "Leo"
    ]
  },
  {
    "code": "264d",
    "name": "Virgo",
    "category": "Symbols",
    "tags": [
      "Virgo"
    ]
  },
  {
    "code": "264e",
    "name": "Libra",
    "category": "Symbols",
    "tags": [
      "Libra"
    ]
  },
  {
    "code": "264f",
    "name": "Scorpio",
    "category": "Symbols",
    "tags": [
      "Scorpio"
    ]
  },
  {
    "code": "2650",
    "name": "Sagittarius",
    "category": "Symbols",
    "tags": [
      "Sagittarius"
    ]
  },
  {
    "code": "2651",
    "name": "Capricorn",
    "category": "Symbols",
    "tags": [
      "Capricorn"
    ]
  },
  {
    "code": "2652",
    "name": "Aquarius",
    "category": "Symbols",
    "tags": [
      "Aquarius"
    ]
  },
  {
    "code": "2653",
    "name": "Pisces",
    "category": "Symbols",
    "tags": [
      "Pisces"
    ]
  },
  {
    "code": "26ce",
    "name": "Ophiuchus",
    "category": "Symbols",
    "tags": [
      "Ophiuchus"
    ]
  },
  {
    "code": "1f5ef_fe0f",
    "name": "anger bubble",
    "category": "Symbols",
    "tags": [
      "anger-bubble"
    ]
  },
  {
    "code": "1f4ac",
    "name": "speech bubble",
    "category": "Symbols",
    "tags": [
      "speech-bubble"
    ]
  },
  {
    "code": "2757",
    "name": "exclamation",
    "category": "Symbols",
    "tags": [
      "exclamation",
      "exclamation-mark"
    ]
  },
  {
    "code": "2753",
    "name": "question",
    "category": "Symbols",
    "tags": [
      "question",
      "question-mark",
      "?"
    ]
  },
  {
    "code": "2049_fe0f",
    "name": "exclamation question mark",
    "category": "Symbols",
    "tags": [
      "exclamation-question-mark",
      "!?"
    ]
  },
  {
    "code": "203c_fe0f",
    "name": "exclamation double",
    "category": "Symbols",
    "tags": [
      "exclamation-double",
      "!!"
    ]
  },
  {
    "code": "274c",
    "name": "cross mark",
    "category": "Symbols",
    "tags": [
      "cross-mark",
      "x"
    ]
  },
  {
    "code": "1f198",
    "name": "sos",
    "category": "Symbols",
    "tags": [
      "sos"
    ]
  },
  {
    "code": "2668_fe0f",
    "name": "hot springs",
    "category": "Symbols",
    "tags": [
      "hot-springs"
    ]
  },
  {
    "code": "1f4f4",
    "name": "phone off",
    "category": "Symbols",
    "tags": [
      "phone-off"
    ]
  },
  {
    "code": "2622_fe0f",
    "name": "radioactive",
    "category": "Symbols",
    "tags": [
      "radioactive"
    ]
  },
  {
    "code": "2623_fe0f",
    "name": "biohazard",
    "category": "Symbols",
    "tags": [
      "biohazard"
    ]
  },
  {
    "code": "26a0_fe0f",
    "name": "warning",
    "category": "Symbols",
    "tags": [
      "warning"
    ]
  },
  {
    "code": "2705",
    "name": "check mark",
    "category": "Symbols",
    "tags": [
      "check-mark",
      "check-mark-green"
    ]
  },
  {
    "code": "1f195",
    "name": "new",
    "category": "Symbols",
    "tags": [
      "new"
    ]
  },
  {
    "code": "1f193",
    "name": "free",
    "category": "Symbols",
    "tags": [
      "free"
    ]
  },
  {
    "code": "1f199",
    "name": "up!",
    "category": "Symbols",
    "tags": [
      "up!"
    ]
  },
  {
    "code": "1f197",
    "name": "ok button",
    "category": "Symbols",
    "tags": [
      "ok-button"
    ]
  },
  {
    "code": "1f192",
    "name": "cool",
    "category": "Symbols",
    "tags": [
      "cool"
    ]
  },
  {
    "code": "1f6ae",
    "name": "litter",
    "category": "Symbols",
    "tags": [
      "litter"
    ]
  },
  {
    "code": "262e_fe0f",
    "name": "peace symbol",
    "category": "Symbols",
    "tags": [
      "peace-symbol"
    ]
  },
  {
    "code": "262f_fe0f",
    "name": "yin yang",
    "category": "Symbols",
    "tags": [
      "yin-yang"
    ]
  },
  {
    "code": "267e_fe0f",
    "name": "infinity",
    "category": "Symbols",
    "tags": [
      "infinity"
    ]
  },
  {
    "code": "1f3b6",
    "name": "musical notes",
    "category": "Symbols",
    "tags": [
      "musical-notes"
    ]
  },
  {
    "code": "2795",
    "name": "plus sign",
    "category": "Symbols",
    "tags": [
      "plus-sign",
      "+"
    ]
  },
  {
    "code": "2122_fe0f",
    "name": "trade mark",
    "category": "Symbols",
    "tags": [
      "trade-mark"
    ]
  },
  {
    "code": "1f3c1",
    "name": "chequered flag",
    "category": "Flags",
    "tags": [
      "chequered-flag"
    ]
  },
  {
    "code": "1f6a9",
    "name": "triangular flag",
    "category": "Flags",
    "tags": [
      "triangular-flag"
    ]
  },
  {
    "code": "1f3f4",
    "name": "black flag",
    "category": "Flags",
    "tags": [
      "black-flag"
    ]
  },
  {
    "code": "1f3f3_fe0f",
    "name": "white flag",
    "category": "Flags",
    "tags": [
      "white-flag"
    ]
  }
] as const
